name: Python

on:
  push:
    branches:
      - main
    paths:
      - "session-management/**"
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "session-management/**"

defaults:
  run:
    working-directory: ./session-management

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.19"
          enable-cache: true
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Lint
        run: bash scripts/lint.sh

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.19"
          enable-cache: true
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Test
        run: bash scripts/test.sh
      - name: Store coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
          include-hidden-files: true
